// Code generated by protoc-gen-go. DO NOT EDIT.
// source: import.proto

package _import

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("import.proto", fileDescriptor_95c01a9edd6a5e10) }

var fileDescriptor_95c01a9edd6a5e10 = []byte{
	// 54 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcc, 0x2d, 0xc8,
	0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0xce, 0x2f, 0xc9, 0x48, 0x2d, 0x82,
	0x70, 0x02, 0x18, 0x92, 0xd8, 0xc0, 0x0c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x4f,
	0x7d, 0x5f, 0x25, 0x00, 0x00, 0x00,
}
